import express from "express";
import supabase from "./supabase.js";

const app = express();
const port = 3002;
app.use(express.json());

//* Reference Object for DB
const gameShape = {
  // id : generated by DB
  title: "Baldur's Gate 3", //text
  creator: "Larian Studios", //text
  description: "Explore the world of Baldur's Gate in this super detailed, turn based rpg, with in depth characters, exploration, and a thrilling story from start to finish.", //text
  tags: "Turn-Based, RPG, Story-focused, Adventure", //text
  price: "69.99" //float8
}

//* Get for all games on the list
app.get("/videogames", async (req, res) => {
  const { data, error } = await supabase.from("Video Games").select("*");

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.status(200).json(data);
});

//* Get for one game searched by id
app.get("/videogames/:id", async (req, res) => {
  const { data, error } = await supabase
    .from("Video Games")
    .select("*")
    .eq("id", req.params.id)
    .single();

  if (error) {
    return res.status(404).json({ error: error.message });
  }

  res.status(200).json(data);
});

//* Post for adding a game to the list
//! Need to add errors for unfilled sections
app.post("/videogames", async (req, res) => {
  const { name, creator, description, tags, price } = req.body;

  const newGame = {
    name,
    creator,
    description,
    tags,
    price,
  };

  const { data, error } = await supabase
    .from("Video Games")
    .insert(newGame)
    .select();

  if (error) {
    return res.status(500).json({ error: error.message });
  }

  res.status(201).json(data);
});

//* Put for editing existing entries
//! May need to add error handling
app.put("/videogames/:id", async (req, res) => {
  const { name, creator, description, tags, price } = req.body;

  const updatedGame = {
    name,
    creator,
    description,
    tags,
    price,
  };

  const { data, error } = await supabase
    .from("Video Games")
    .update(updatedGame)
    .eq("id", req.params.id)
    .select();

  if (error) {
    return res.status(404).json({ error: error.message });
  }

  return res.status(201).json(data[0]);
});

//* Delete for removing a game from the list by id
app.delete("/videogames/:id", async (req, res) => {
  const { data, error } = await supabase
    .from("Video Games")
    .delete()
    .eq("id", req.params.id);

  if (error) {
    return res.status(404).json({ error: error.message });
  }

  return res.status(200).json({ message: "Game deleted successfully " });
});

//* Tells what port im on
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
